version: "3.9"

services:
    database_rentcar:
        image: postgres
        container_name: database_rentcar
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=rentcar
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: rentcar
        ports:
            - "3333:3333"
            - "9229:9229"
        volumes:
            - .:/usr/app
        links:
            - database_rentcar
        depends_on:
            - database_rentcar
volumes:
    pgdata:
        driver: local
