POST {{baseURL}}/categories/import
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file"

< /Users/dr.aseel/Downloads/1615818549022-attachment.csv
--WebAppBoundary--

###
GET {{baseURL}}/categories
Accept: application/json

###
POST {{baseURL}}/categories
Content-Type: application/json

{
    "name": "EV",
    "description": "No need for gasoline"
}

### add a new category
