GET {{baseURL}}/categories
Accept: application/json

###
POST {{baseURL}}/categories
Content-Type: application/json

{
    "name": "BMW",
    "description": "The fastest car"
}

### add a new category
