### import category from csv file
POST {{baseURL}}/categories/import
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file"

< /Users/dr.aseel/Downloads/1615818549022-attachment.csv
--WebAppBoundary--

### list all categories
GET {{baseURL}}/categories
Accept: application/json

### create a new category
POST {{baseURL}}/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "EV",
    "description": "No need for gasoline"
}

### add a new category
