### list all specifications
GET {{baseURL}}/specifications
Accept: application/json

### create a new specification
POST {{baseURL}}/specifications
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "solar cars",
    "description": "tesla cars"
}

###
