PATCH {{baseURL}}/users
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{token}}

--WebAppBoundary
Content-Disposition: form-data; name="avat"; filename="avatar.jpeg"

< /Users/dr.aseel/Downloads/mustafa.jpeg
--WebAppBoundary--

###
POST {{baseURL}}/session
Content-Type: application/json

{
    "email": "admin@email.com",
    "password": "admin"
}

###
POST {{baseURL}}/users
Content-Type: application/json

{
    "name": "Mustafa",
    "email": "hamandoshm@hotmail.com",
    "password": "12345678",
    "driver_license": "!DW@"
}

###
